# Generated by Django 3.2.16 on 2023-05-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230516_1747'),
        ('inventarioApp', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor_unitario', models.IntegerField()),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='proveedor_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.proveedores')),
            ],
        ),
        migrations.RenameModel(
            old_name='permisos',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='sucursales',
            old_name='id_devolucion',
            new_name='devolucion',
        ),
        migrations.RenameField(
            model_name='sucursales',
            old_name='id_entrada',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='sucursales',
            old_name='id_salida',
            new_name='salida',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id_mercancia',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_maxima',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_minima',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='responsable',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='mercancia',
        ),
        migrations.AddField(
            model_name='producto_inventario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.inventario'),
        ),
        migrations.AddField(
            model_name='producto_inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.productos'),
        ),
    ]
