# Generated by Django 3.2.16 on 2023-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0005_auto_20230525_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercancia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
