# Generated by Django 3.2.16 on 2023-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0006_alter_entradamercancia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionmercancia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salidamercancia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
