# Generated by Django 3.2.16 on 2023-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0008_auto_20230611_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursales',
            name='devolucion',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='salida',
        ),
    ]
