# Generated by Django 3.2.16 on 2023-06-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0009_auto_20230617_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionmercancia',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.sucursales'),
        ),
        migrations.AddField(
            model_name='entradamercancia',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.sucursales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidamercancia',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.sucursales'),
            preserve_default=False,
        ),
    ]
