# Generated by Django 3.2.16 on 2023-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0011_auto_20230630_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
