# Generated by Django 3.2.16 on 2023-07-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0012_alter_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
