# Generated by Django 3.2.16 on 2023-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0014_sucursales_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
