# Generated by Django 3.2.16 on 2023-07-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0015_categorias_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
