# Generated by Django 3.2.16 on 2023-07-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0016_alter_categorias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercancia',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.producto_inventario'),
        ),
    ]
