# Generated by Django 3.2.16 on 2023-07-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0018_rename_id_sucursal_inventario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercancia',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.sucursales'),
        ),
    ]
