# Generated by Django 3.2.16 on 2023-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230621_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_permisos',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Gestión de proveedores'), (2, 'Gestión de movimientos')], default=0),
        ),
    ]
